### ISSUE TITLE
Implement "help_aboutdevices" contents

### ISSUE THREAD

**Issue by farzanehfar** [ideafast/ideafast-patientapp#7]
It should have all the devices with images and all the information about them.

please check the design:

https://xd.adobe.com/view/cc9640fb-7dc6-4886-46c3-f9324e81f8a4-baa7/screen/cffc1d75-1100-4262-9da7-a9d2b552d308/HELP
[Pictures.docx](https://github.com/ideafast/ideafast-patientapp/files/4656257/Pictures.docx)

**Comment by jawrainey** [comment]
@farzanehfar | @b9019367  -- I would hold off using the device images in the attached document as placeholder until we have high-quality SVGs for each device from the manufactures. Instead, use a placeholder SVG in place of the device image. This is because they will change in the future and the attached docx will compress/reduce quality of the images anyway  👍

**Comment by farzanehfar** [comment]
Try this solution in this branch:

I think the issue with useNativeDriver could potentially be solved by upgrading the dropdown item package. 'react-native-dropdown-item' is deprecated, so we should use https://www.npmjs.com/package/@dooboo-ui/native-accordion instead - which is being actively maintained, and is the successor of that package.
